# Generated by Django 3.2.3 on 2021-12-09 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=60, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone_id', models.CharField(blank=True, max_length=10, null=True)),
                ('drone_type', models.CharField(blank=True, max_length=30, null=True)),
                ('user_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, max_length=30, null=True)),
                ('admisiion_number', models.CharField(blank=True, max_length=25, null=True)),
                ('title', models.CharField(blank=True, max_length=5, null=True)),
                ('f_name', models.CharField(max_length=20, verbose_name=':First Name')),
                ('m_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Middle Name')),
                ('l_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('marital_status', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=3, null=True)),
                ('dob', models.CharField(blank=True, max_length=20, null=True)),
                ('nationality', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=13, null=True)),
                ('house_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ghana_post_number', models.CharField(blank=True, max_length=20, null=True)),
                ('region', models.CharField(blank=True, max_length=20, null=True)),
                ('Phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('insurance_company', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutPatientDepartment_opd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opd_number', models.CharField(blank=True, max_length=30, null=True)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('temperature', models.CharField(blank=True, max_length=10, null=True)),
                ('patient_complains', models.TextField(blank=True, max_length=200, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DroneUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('f_name', models.CharField(blank=True, max_length=30, null=True)),
                ('l_name', models.CharField(blank=True, max_length=30, null=True)),
                ('drone_type', models.CharField(blank=True, max_length=20, null=True)),
                ('drone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.drone')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(blank=True, max_length=15, null=True)),
                ('f_name', models.CharField(max_length=30)),
                ('m_name', models.CharField(blank=True, max_length=30, null=True)),
                ('l_name', models.CharField(max_length=30)),
                ('doc_phoneNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('doc_email', models.CharField(blank=True, max_length=60, null=True, verbose_name='Email')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.patient')),
            ],
        ),
    ]
