# Generated by Django 3.2.3 on 2021-12-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='f_name',
            field=models.CharField(max_length=20, verbose_name='First Name'),
        ),
    ]
