# Generated by Django 3.2.3 on 2021-12-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_patient_f_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('l_name', 'f_name', 'm_name')},
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=3, null=True),
        ),
    ]
