# Generated by Django 3.2.3 on 2021-12-09 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211209_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
