# Generated by Django 3.2.3 on 2021-12-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_patient_create_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
    ]
