# Generated by Django 3.2.3 on 2021-12-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_patient_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Phone_number',
            new_name='phone_number',
        ),
    ]
