# Generated by Django 3.2.3 on 2021-12-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_phone_number_patient_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='f_name',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='l_name',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='m_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Middle Name'),
        ),
    ]
