# Generated by Django 3.2.3 on 2021-12-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20211210_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
