# Generated by Django 3.2.3 on 2021-12-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_admin_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='droneuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='drone_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Drone ID'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='user_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='droneuser',
            name='f_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='droneuser',
            name='l_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Last Name'),
        ),
    ]
